version: "3"

services:
  app:
    restart: always
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    # ports:
    #   - 8000:8000
    expose:
      - 5000
    environment:
      - PORT=5000
      - MLFLOW_BACKEND_STORE_PATH=postgresql://pg:pg@db:5432/pg
      - MLFLOW_ARTIFACT_PATH=file:///mnt/data/artifacts
      - MLFLOW_TRACKING_USERNAME=nhung
      - MLFLOW_TRACKING_PASSWORD=28102024
    volumes:
      - /mnt/data-on/mlflow-nhung/artifacts:/mnt/data/artifacts
    depends_on:
      - db
    networks:
      - mlflow-network

  db:
    container_name: db
    restart: always
    image: postgres:14
    expose:
      - 5432
    environment:
      - POSTGRES_DB=pg
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
    volumes:
      - /mnt/data-on/mlflow-nhung/db:/var/lib/postgresql/data
      # - ./db:/var/lib/postgresql/data
    networks:
      - mlflow-network
  
  nginxauth:
      depends_on: 
        - app
      restart: always
      build: ./nginx
      image: nginxauthformlflow
      ports:
        - 9000:80
      networks:
        - mlflow-network

networks:
  mlflow-network: null
