version: "3"

services:
  mlflow-tracking:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - MLFLOW_BACKEND_STORE_PATH=postgresql://pg:pg@db:5432/pg
      - MLFLOW_ARTIFACT_PATH=file:///home/cuongnguyen/mlflow-tracking/data/artifacts
      - MLFLOW_TRACKING_USERNAME=cuong
      - MLFLOW_TRACKING_PASSWORD=cuong
    volumes:
      - /mnt/data/mlflow/data/artifacts:/home/cuongnguyen/mlflow-tracking/data/artifacts
    depends_on:
      - db
    networks:
      - mlflow-network

  db:
    container_name: db
    restart: always
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_DB=pg
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
    volumes:
      - /mnt/data/mlflow/data/db:/var/lib/postgresql/data
    networks:
      - mlflow-network

networks:
  mlflow-network: null
