apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking
  labels:
    app: mlflow-tracking
    service: mlflow-tracking
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: mlflow-tracking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking
spec:
  replica: 1
  selector:
    matchLabels:
      app: mlflow-tracking
  template:
    metadata:
      labels:
        app: mlflow-tracking
    spec:
      containers:
        - name: mlflow-tracking
          image: nndcuong/mlflow-tracking
          imagePullPolicy: Always
          env:
            - name: MLFLOW_ARTIFACT_PATH
              value: s3://ai-parsecv-model/mlflow-artifacts
        - name: db
          image: postgres
          env:
            - name: POSTGRES_DB
              value: pg
            - name: POSTGRES_USER
              value: pg
            - name: POSTGRES_PASSWORD
              value: pg
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          imagePullPolicy: IfNotPresent
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: mlflow-tracking-backend
      restartPolicy: Always
