apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc  # Sets name of PVC
  namespace: mlflow-tracking
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
