apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-registry-pvc  # Sets name of PVC
  namespace: mlflow-tracking
  labels:
    app: mlflow-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
