apiVersion: v1
kind: Service
metadata:
  name: mlflow # Sets service name
  namespace: mlflow-tracking
  labels:
    app: mlflow # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 80 # Sets port to run the mlflow application
      nodePort: 30001
  selector:
    app: mlflow
